config/routes.rb
App2::Application.routes.draw do

 
  resources :students do
    resources :courses
  end
   
  resources :courses do
    member do
     get :up
    end
   collection do
    get :latest
   end
 end

 

  match 'students' => 'students#index'
  root :to => "students#index"

  

  match ':controller(/:action(/:id(.:format)))'

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
   has_many :courses, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
 
  def show
    @course = Course.find(params[:id])
    @student_course = Student.find(params[:student_id])
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @course = Student.find(params[:student_id]).courses.new
  end

  def create
    student = Student.find(params[:student_id])
    student.courses.create(params[:course])
    redirect_to student
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.xml
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @students }
    end
  end

  # GET /students/1
  # GET /students/1.xml
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/new
  # GET /students/new.xml
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.xml
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to(@student, :notice => 'Student was successfully created.') }
        format.xml  { render :xml => @student, :status => :created, :location => @student }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.xml
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to(@student, :notice => 'Student was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.xml
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to(students_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_form.html.erb
<%= form_for([@course.student, @course]) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.text_field :points %>
  </div>
  <div class="field">
    <%= f.label :mandatory %><br />
    <%= f.check_box :mandatory %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @course.name %>
</p>

<p>
  <b>Points:</b>
  <%= @course.points %>
</p>

<p>
  <b>Mandatory:</b>
  <%= @course.mandatory %>
</p>

<%= link_to 'Back', student_path(@student_course) %>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pesel %><br />
    <%= f.text_field :pesel %>
  </div>
  <div class="field">
    <%= f.label :semester %><br />
    <%= f.text_field :semester %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
   <!--  <td><%= student.pesel %></td> -->
   <!-- <td><%= student.semester %></td>  -->
    <td><%= link_to 'Show more', student %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Pesel:</b>
  <%= @student.pesel %>
</p>

<p>
  <b>Semester:</b>
  <%= @student.semester %>
</p>

<b> Courses: </b>
<table>
 <% @student.courses.each do |course| %>
 <tr>
 <td><%= course.name %> </td>
 <td><%= link_to 'Show more', student_course_path(course.student_id, course.id) %></td> 
 </tr>
<% end %>
</table>

<br />

<%= link_to 'Back', students_path %>
<%= link_to 'New course', new_student_course_path(@student) %>